config/routes.rb
Rails.application.routes.draw do
  resources :categories do 
    resources :posts, only: [:index, :new, :create]
  end
  
  resources :favorites

  resources :posts do
    resources :likes
    resources :comments
  end
  
  #root('static#home')
  root('posts#topups')
  get '/about', to: 'static#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/mylist', to: 'posts#mylist', as: 'mylist'
  get '/topups', to: 'posts#topups', as: 'topups'
  get '/kups', to: 'posts#kups', as: 'kups'
  get '/newups', to: 'posts#newups', as: 'newups'
  get '/search', to: 'posts#search', as: 'search'
  get '/search_by_username', to: 'posts#search_by_username', as: 'search_by_username'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_many :favorite_posts
    has_many :posts, through: :favorite_posts
    belongs_to :user
    validates :name, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    before_action :set_favorite, only: [:show, :update, :edit, :destroy]
    def new
        @favorite = Favorite.new
    end

    def create
        @favorite = current_user.favorites.build(favorite_params)
        if @favorite.save
            redirect_to favorite_path(@favorite)
        else
            render :new
        end    
    end

    def index
        if current_user.favorites.empty?
            flash[:message] = "You don't have any list yet why don't you make one"
            redirect_to new_favorite_path
        else
            @favorites=current_user.favorites
        end
    end

    def edit

    end

    def update
        @favorite.update(favorite_params)

        if @favorite.valid?
            redirect_to favorite_path(@favorite)
        else
            flash[:message] = "Unable to update"
            render :edit
        end
    end

    def show
        
    end

    def destroy
        @favorite.destroy
        redirect_to favorites_path
    end

    private
    def set_favorite
        @favorite=Favorite.find_by(id: params[:id])
    end

    def favorite_params
        params.require(:favorite).permit(:name, :user_id, post_ids: [])
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/edit.html.erb
<h1> Edit Favorite List</h1>
<%= form_with(model: @favorite) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.collection_check_boxes :post_ids, Post.all, :id, :title %>
    <br><br>
    <%= f.submit "Create" %>
<% end %>

app/views/favorites/index.html.erb
<h1>My favorites</h1>
<%=link_to 'Create New List', new_favorite_path %><br>

<% @favorites.each do |f| %>
    <li><%=link_to f.name, favorite_path(f)%></li>
<% end %>

app/views/favorites/new.html.erb
<h1> Create New Favorite List</h1>
<%= form_with(model: @favorite) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.collection_check_boxes :post_ids, Post.all, :id, :title %>
    <br><br>
    <%= f.submit "Create" %>
<% end %>

app/views/favorites/show.html.erb
<h1><%=@favorite.name%> list</h1>
<% if logged_in? && current_user==@favorite.user %>
    <div class="btn-group">
        <%= button_to "Edit", edit_favorite_path(@favorite), method: 'get'%>
        <%= button_to 'Delete', @favorite, method: 'delete' %>
    </div>
    <br>
<% end %>
<% @favorite.posts.each do |p| %>
    <li><%=link_to p.title, post_path(p) %></li>
<% end %>