config/routes.rb
Rails.application.routes.draw do
  resources :categories do 
    resources :posts, only: [:index, :new, :create]
  end
  
  resources :favorites

  resources :posts do
    resources :likes
    resources :comments
  end
  
  #root('static#home')
  root('posts#topups')
  get '/about', to: 'static#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/mylist', to: 'posts#mylist', as: 'mylist'
  get '/topups', to: 'posts#topups', as: 'topups'
  get '/kups', to: 'posts#kups', as: 'kups'
  get '/newups', to: 'posts#newups', as: 'newups'
  get '/search', to: 'posts#search', as: 'search'
  get '/search_by_username', to: 'posts#search_by_username', as: 'search_by_username'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :content, presence: true

    def comment_date
        created_at.strftime("%m. %d. %Y")
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_many :favorite_posts
    has_many :posts, through: :favorite_posts
    belongs_to :user
    validates :name, presence: true
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
    belongs_to :post
	belongs_to :favorite
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category, optional: true 
    has_many :favorite_posts
    has_many :favorites, through: :favorite_posts
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :users, through: :comments
    has_many :likes, dependent: :destroy
    has_one_attached :image, dependent: :destroy
    #has_many_attached :images, dependent: :destroy
    validates :title, presence: true

    scope :newups, -> {order created_at: :desc}
    scope :topups, -> {order views: :desc}
    scope :kups, -> { 
        select('posts.*, COUNT(likes.post_id) AS likes_count')
        .joins(:likes)
        .group('post_id')
        .order('likes_count DESC')
    }
    scope :search, -> (query) { self.where("title LIKE ?", "%#{query}%") }
    scope :search_by_username, -> (query) {
        joins(:user)
        .where('users.username LIKE ?', "%#{query}%")
    }

    def category_attributes=(attributes)
        if !(attributes[:name].blank?)
            self.category = Category.find_or_create_by(attributes)
        end
    end
    
    def post_date
        created_at.strftime("%m. %d. %Y")
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :favorites
    has_many :uploaded_posts, foreign_key: "user_id", class_name: "Post"
    has_many :comments
    has_many :posts, through: :comments
    
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true 

    def full_name
        first_name+" "+last_name
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_post
    def create
        @comment = @post.comments.build(comment_params)
        if @comment.save
            flash[:message] = "You Commented this post"
            redirect_to post_path(@post)
        else
            flash[:message] = "Something went wrong, try again"
            redirect_to post_path(@post)
        end

    end

    private
    def find_post
        @post = Post.find_by(id: params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:user_id, :post_id, :content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_post  
    def create
        if @post.user_id == current_user.id
            flash[:message] = "You can't like this posts since you uploaded it"  
        elsif already_liked?
            flash[:message] = "You can't like more than once"
        else
            @post.likes.create(user_id: current_user.id)
        end
        redirect_to post_path(@post)
    end  

    private  
    def find_post
        @post = Post.find_by(id: params[:post_id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_post, only: [:show, :update, :edit, :destroy]
    before_action :find_category, only: [:index, :new, :create]
    def index    
        if @category 
            @posts=@category.posts
        else
            @posts=Post.all
        end
    end

    def mylist
        if current_user.uploaded_posts.empty?
            flash[:message] = "You haven't post anything yet why don't you post one"
            redirect_to new_post_path
        else 
            @posts=current_user.uploaded_posts
        end
        #elsif @category
        #    @posts=[]
        #    @category.posts.each do |p|
        #        if p.user_id==current_user.id
        #            @posts << p
        #        end 
        #    end
        #else
        #    @posts=current_user.uploaded_posts
        #end
    end

    def show
        @post.update(views: @post.views+1)
        @comments = @post.comments
    end

    def new
        if @category
            @post = @category.posts.build
        else
            @post = Post.new
            @post.build_category
        end
    end
    
    def create
        @post = Post.new(post_params)
        @post.image.attach(params[:post][:image])
        
        if @post.save
            if @category
                redirect_to category_posts_path(@category)
            else
                redirect_to post_path(@post)
            end
        else
            render :new
        end
    end

    def edit
    end

    def update
        @post.update(post_params)
        if @post.valid?
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    def topups
        @posts=Post.topups
    end

    def kups
        @posts=Post.kups
    end

    def newups
        @posts=Post.newups
    end

    def search
        @posts = Post.search(params[:title])
        render :index
    end

    def search_by_username
        @posts = Post.search_by_username(params[:username])
        render :index
    end

    private
    def set_post
        @post=Post.find_by(id: params[:id])
    end

    def post_params
        params.require(:post).permit(:user_id, :title, :link, :content, :image, :category_id, category_attributes: [:name])
    end

    def find_category
        @category = Category.find_by_id(params[:category_id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new, :create]
    def new
        @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:message] = "Welcome to Up, #{@user.full_name}!"
            session[:user_id] = @user.id
            redirect_to posts_path
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:last_name, :first_name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_posts_helper.rb
module FavoritePostsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_fields_for.html.erb
<h3> Select existing Category </h3>
<%= f.collection_select(:category_id, Category.all, :id, :name) %>

app/views/posts/_form.html.erb
<div class="text-center">
    <h1><%= form_title %></h1>
</div>
<%= form_with(model: model) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control input-lg" %>
   
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control input-lg" %>
    
    <%= f.label :link %>
    <%= f.text_field :link, class: "form-control input-lg" %>
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control input-lg" %>
    <% if @category %>
        <%= f.hidden_field :category_id, value: @category.id %> 
    <%else%>
        <%= render partial: "fields_for", locals: {f: f}  %>
    <%end %>
    <%= f.submit button_name %>
<% end %>

app/views/posts/_post.html.erb
<div  class="card">
    <div class="row no-gutters">
        <div class="col-auto">
            <% if !post.link.empty? %>
                <%= image_tag(post.link, width: 300, height: 300, style: "float:left") %><br>
            <% end %>
            <% if post.image.attached?%>
                <%= image_tag(post.image, width: 300, height: 300, style: "float:left") %> 
            <% end %>
        </div>
        <div class="col">
            <div class="card-block px-2">
                <br><br>
                <h3><%= link_to post.title, post_path(post), class: "text-dark" %></h3>
                <h4><%= post.user.username %></h4><p><%= post.post_date %><p> <br>
                <h4><%= image_tag('view.png', width: '25px', height: '25px')%><%= post.views %> 
                <%= image_tag('ThumbsUp.png', width: '25px', height: '25px')%><%= post.likes.count %>
                <%= image_tag('comment.png', width: '25px', height: '25px')%><%= post.comments.count %>
            </div>
        </div>
    </div>
</div>
<br>

app/views/posts/edit.html.erb
<%= render partial: 'form', locals: { form_title: "Edit Post", model: @post, button_name: "Edit Post" } %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% if @category %>
    <h2>Category: <%= @category.name %></h2><br>
    <%= link_to "Make new post for this category", new_category_post_path(@category) %>
<% end %>
<%= render @posts %>

app/views/posts/kups.html.erb
<h1>1KUps</h1>
<%= render @posts%>

app/views/posts/mylist.html.erb
<h1>My Uploaded list</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<%= render partial: 'static/errors', locals: {model: @post} %>

<div class="text-center">
    <h1><%= "New Post" %></h1>
</div>
<%= form_with(model: [@category, @post]) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control input-lg" %>
   
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control input-lg" %>
    
    <%= f.label :link %>
    <%= f.text_field :link, class: "form-control input-lg" %>
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control input-lg" %>
    <% if @category %>
        <%= f.hidden_field :category_id, value: @category.id %> 
    <%else%>
        <%= render partial: "fields_for", locals: {f: f}  %>
    <%end %>
    <%= f.submit "Create Post" %>
<% end %>

app/views/posts/newups.html.erb
<h1>NewUps</h1>
<%= render @posts %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><strong>by <%= @post.user.username %></strong> <%= @post.post_date %></p>
<% if logged_in? && current_user==@post.user %>
    <div class="btn-group">
        <%= button_to "Edit", edit_post_path(@post), method: 'get'%>
        <%= button_to 'Delete', @post, method: 'delete' %>
    </div>
    <br>
<% end %>

<% if @post.link %>
    <%= image_tag(@post.link) %><br>
<% end %>

<% if @post.image.attached?%>
    <%= image_tag(@post.image) %>
<% end %>
<br>
<h4><%= @post.content %></h4><br>

<h4><%= image_tag('view.png', width: '25px', height: '25px')%><%= @post.views %> 
<%= link_to image_tag('ThumbsUp.png', width: '25px', height: '25px'), post_likes_path(@post), method: :post %><%= @post.likes.count %></h4><br> 

<h4>comments <%= @comments.count %></h4>
<% if logged_in? %>
    <%= form_with(model: [@post, @comment = current_user.comments.build()]) do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :image_id, value: @post.id %>
        <%= f.text_field :content %>
        <%= f.submit :comment %>
    <% end %>
<% end %>
<ul>   
    <% @comments.each do |comment| %>
        <li>
            <p><strong><%= comment.user.username %></strong> <%= comment.comment_date %> </p>
            <p><%= comment.content %></p>
        </li>
    <% end %>
</ul>
<br>
<br>

app/views/posts/topups.html.erb
<h1>TopUps</h1>
<%= render @posts %>

app/views/users/new.html.erb
<%= render partial: 'static/errors', locals: {model: @user} %>
<%= form_with(model: @user, url: signup_path) do |f| %>
    <div class="text-center">
        <%= image_tag("avatar.jpg", alt: "User", width: 250, height: 250) %>
    </div>
    <div class="row">
        <div class="col">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, required: true, class: "form-control input-lg" %><br>
        </div>
        <div class="col">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, required: true, class: "form-control input-lg" %><br>
        </div>
    </div>
    <%= f.label :username %>
    <%= f.text_field :username, required: true, class: "form-control input-lg" %><br>
    <%= f.label :email %>
    <%= f.email_field :email, required: true, class: "form-control input-lg" %><br>
    <%= f.label :password %>
    <%= f.password_field :password, required: true, class: "form-control input-lg" %><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, required: true, class: "form-control input-lg" %><br>
    <div class="text-center">
        <%= f.submit "Sign Up" %>
    </div>
<% end %>