config/routes.rb
Rails.application.routes.draw do
  resources :categories do 
    resources :posts, only: [:index, :new, :create]
  end
  
  resources :favorites

  resources :posts do
    resources :likes
    resources :comments
  end
  
  #root('static#home')
  root('posts#topups')
  get '/about', to: 'static#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/mylist', to: 'posts#mylist', as: 'mylist'
  get '/topups', to: 'posts#topups', as: 'topups'
  get '/kups', to: 'posts#kups', as: 'kups'
  get '/newups', to: 'posts#newups', as: 'newups'
  get '/search', to: 'posts#search', as: 'search'
  get '/search_by_username', to: 'posts#search_by_username', as: 'search_by_username'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :content, presence: true

    def comment_date
        created_at.strftime("%m. %d. %Y")
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_many :favorite_posts
    has_many :posts, through: :favorite_posts
    belongs_to :user
    validates :name, presence: true
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
    belongs_to :post
	belongs_to :favorite
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category, optional: true 
    has_many :favorite_posts
    has_many :favorites, through: :favorite_posts
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :users, through: :comments
    has_many :likes, dependent: :destroy
    has_one_attached :image, dependent: :destroy
    #has_many_attached :images, dependent: :destroy
    validates :title, presence: true

    scope :newups, -> {order created_at: :desc}
    scope :topups, -> {order views: :desc}
    scope :kups, -> { 
        select('posts.*, COUNT(likes.post_id) AS likes_count')
        .joins(:likes)
        .group('post_id')
        .order('likes_count DESC')
    }
    scope :search, -> (query) { self.where("title LIKE ?", "%#{query}%") }
    scope :search_by_username, -> (query) {
        joins(:user)
        .where('users.username LIKE ?', "%#{query}%")
    }

    def category_attributes=(attributes)
        if !(attributes[:name].blank?)
            self.category = Category.find_or_create_by(attributes)
        end
    end
    
    def post_date
        created_at.strftime("%m. %d. %Y")
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :favorites
    has_many :uploaded_posts, foreign_key: "user_id", class_name: "Post"
    has_many :comments
    has_many :posts, through: :comments
    
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true 

    def full_name
        first_name+" "+last_name
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_post  
    def create
        if @post.user_id == current_user.id
            flash[:message] = "You can't like this posts since you uploaded it"  
        elsif already_liked?
            flash[:message] = "You can't like more than once"
        else
            @post.likes.create(user_id: current_user.id)
        end
        redirect_to post_path(@post)
    end  

    private  
    def find_post
        @post = Post.find_by(id: params[:post_id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_post, only: [:show, :update, :edit, :destroy]
    before_action :find_category, only: [:index, :new, :create]
    def index    
        if @category 
            @posts=@category.posts
        else
            @posts=Post.all
        end
    end

    def mylist
        if current_user.uploaded_posts.empty?
            flash[:message] = "You haven't post anything yet why don't you post one"
            redirect_to new_post_path
        else 
            @posts=current_user.uploaded_posts
        end
        #elsif @category
        #    @posts=[]
        #    @category.posts.each do |p|
        #        if p.user_id==current_user.id
        #            @posts << p
        #        end 
        #    end
        #else
        #    @posts=current_user.uploaded_posts
        #end
    end

    def show
        @post.update(views: @post.views+1)
        @comments = @post.comments
    end

    def new
        if @category
            @post = @category.posts.build
        else
            @post = Post.new
            @post.build_category
        end
    end
    
    def create
        @post = Post.new(post_params)
        @post.image.attach(params[:post][:image])
        
        if @post.save
            if @category
                redirect_to category_posts_path(@category)
            else
                redirect_to post_path(@post)
            end
        else
            render :new
        end
    end

    def edit
    end

    def update
        @post.update(post_params)
        if @post.valid?
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    def topups
        @posts=Post.topups
    end

    def kups
        @posts=Post.kups
    end

    def newups
        @posts=Post.newups
    end

    def search
        @posts = Post.search(params[:title])
        render :index
    end

    def search_by_username
        @posts = Post.search_by_username(params[:username])
        render :index
    end

    private
    def set_post
        @post=Post.find_by(id: params[:id])
    end

    def post_params
        params.require(:post).permit(:user_id, :title, :link, :content, :image, :category_id, category_attributes: [:name])
    end

    def find_category
        @category = Category.find_by_id(params[:category_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new, :create]
    def new
        @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:message] = "Welcome to Up, #{@user.full_name}!"
            session[:user_id] = @user.id
            redirect_to posts_path
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:last_name, :first_name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Up</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <header class="p-3 mb-3 border-bottom bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start" id="menu">
          <%= link_to image_tag('Logo.png', width: '30px', height: '30px'), root_path %>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <%= link_to "AboutUps", about_path, class: "nav-link px-2 link-info" %>
            <%= link_to "TopUps", topups_path, class: "nav-link px-2 text-white" %>
            <%= link_to "1KUps", kups_path, class: "nav-link px-2 text-white" %>
            <%= link_to "NewUps", newups_path, class: "nav-link px-2 text-white" %>
            <div class="dropdown text-end">
                <a href="#" class="nav-link px-2 text-white dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Category
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                  <li><%= link_to "Fun", category_posts_path(1), class: "dropdown-item" %></li>
                  <li><%= link_to "Touching", category_posts_path(2), class: "dropdown-item" %></li>
                  <li><%= link_to "Cute", category_posts_path(3), class: "dropdown-item" %></li>
                  <li><%= link_to "Weird", category_posts_path(4), class: "dropdown-item" %></li>
                  <li><%= link_to "Etc", category_posts_path(5), class: "dropdown-item" %></li>
                </ul>
            </div>
            
            <% if !logged_in? %>
              <%= link_to "Signup", signup_path, class: "nav-link px-2 text-white" %>
              <%= link_to "Login", login_path, class: "nav-link px-2 text-white" %>
            <% end %>
          </ul> 
          <%= form_with(url: search_path, method: 'get', class: 'd-flex') do |f|%>
          <%= f.text_field :title, class: "form-control me-2", placeholder: "Search for Title" %>
          <%= f.submit :Search, class: "btn btn-outline-success" %>
          <% end %>
          <%= form_with(url: search_by_username_path, method: 'get', class: 'd-flex') do |f|%>
          <%= f.text_field :username, class: "form-control me-2", placeholder: "Search by username" %>
          <%= f.submit :Search, class: "btn btn-outline-success" %>
          <% end %>
        
          <% if logged_in? %>
            <div class="dropdown text-end">
                <a href="#" class="d-block link-info text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= image_tag("avatar.jpg", alt: "User", width: 32, height: 32, class: "rounded-circle") %>
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                  <li><%= link_to "My posts", mylist_path, class: "dropdown-item" %></li>
                  <li><%= link_to "My favorites", favorites_path, class: "dropdown-item" %></li>
                  <li><%= link_to "New post", new_post_path, class: "dropdown-item" %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to "Sign out", logout_path, method: "delete", class: "dropdown-item" %></li>
                </ul>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <div class="container">
      <div class="text-dark bg-warning">
        <%= flash[:message]%>
      </div>
      
      <%= yield %>
    </div>
  </body>
</html>